<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('translations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('language_id')->constrained('languages')->onDelete('cascade');
            $table->string('group')->nullable()->comment('Translation group/namespace');
            $table->string('key')->comment('Translation key (md5 of original string)');
            $table->text('value')->comment('Translated text value');
            $table->boolean('is_active')->default(true)->comment('Whether the translation is active');
            $table->boolean('is_auto_translated')->default(false)->comment('Whether translation was generated by AI');
            $table->unsignedBigInteger('translated_by_user_id')->nullable()->comment('User who created/updated the translation');
            $table->timestamps();

            $table->unique(['language_id', 'group', 'key'], 'translations_unique');
            $table->index(['language_id', 'key']);
            $table->index(['language_id', 'group']);
            $table->index(['group', 'key', 'language_id'], 'translations_lookup');
            $table->index('key');
            $table->index('group');
            $table->index('is_active');
            $table->index('created_at');
            $table->index('updated_at');
        });

        if (DB::connection()->getDriverName() === 'mysql') {
            DB::statement('ALTER TABLE translations ADD FULLTEXT INDEX idx_translations_fulltext (key, value)');
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('translations');
    }
};
