<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('translations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('language_id')->constrained('languages')->onDelete('cascade');
            $table->string('group')->nullable()->index()->comment('Translation group/namespace');
            $table->string('key')->index()->comment('Translation key');
            $table->text('value')->comment('Translated text value');
            $table->boolean('is_active')->default(true)->index()->comment('Whether the translation is active');
            $table->boolean('is_auto_translated')->default(false)->comment('Whether translation was generated by AI');
            $table->unsignedBigInteger('translated_by_user_id')->nullable()->comment('User who created/updated the translation');
            $table->timestamps();

            // Composite unique index to prevent duplicate translations
            $table->unique(['language_id', 'group', 'key'], 'translations_unique');

            // Index for common queries
            $table->index(['group', 'key', 'language_id'], 'translations_lookup');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('translations');
    }
};
